### ISSUE TITLE
what is the difference between OpenAiKey and OpenAiApiKey in the .env file?

### ISSUE THREAD

**Issue by Mshz2** [akshata29/entaoai#40]

**Comment by akshata29** [comment]
@Mshz2  - OpenAiKey is used when you select Azure OpenAI as the LLM model.  OpenAiApiKey is used if instead you selected OpenAI as the LLM model.  Eventually we will be adding the hugging face/OSS and other models.

Hope that helps

**Comment by raffertyuy** [comment]
Ah! Got it thanks!

> @Mshz2 - OpenAiKey is used when you select Azure OpenAI as the LLM model. OpenAiApiKey is used if instead you selected OpenAI as the LLM model. Eventually we will be adding the hugging face/OSS and other models.
> 
> Hope that helps
